server:
  port: 8768
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/feifuzeng/SpringcloudConfig
          search-paths: respo
          username:
          password:
      label: master
  application:
    name: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


